# Decision Trees & Markov Models

## Decision Trees

**Base Case: Terminal Node**

* All data is of same class.
* Information Gain is 0.

**Recursive Case: Decision Node**

* Record most common classification at this node. (**missing values**)
* For each (remaining) attribute: compute gain ratio
* Add new nodes for split (recursive step)

## Test/Train Split

Given a set of labeled records, we split it to train on some portion & test our accuracy on the other.

**Why not train on 100%?**

- No way to evaluate accuracy.
- Recall the "employee ID" case -- bad correlations are possible.
- High likelihood of overfitting.

Tradeoff between accuracy of model & ability to measure accuracy vs. potential accuracy.

Can also have different computational costs (e.g. if evaluating model is expensive, might favor smaller test set.).

### Markov Models

**Markov process**: process in which each event is dependent only upon current state.

**Die Roll Example**

**Hashtable Representation**

**Matrix Representation**

It is also common to encode these models in a Matrix.

Probability of transitioning from (row) to (col):

| | Sunny | Cloudy | Rainy |
|--|-----|----|----|
| Sunny | 0.7 | 0.2 | 0.1 |
| Cloudy | 0.5 | 0.3 | 0.2 |
| Rainy | 0.3 | 0.3 | 0.4 |

In [8]:
import numpy as np

In [14]:
model = np.array([[0.7, 0.2, 0.1], [0.5, 0.3, 0.2], [0.3, 0.3, 0.4]])
model

array([[0.7, 0.2, 0.1],
       [0.5, 0.3, 0.2],
       [0.3, 0.3, 0.4]])

In [51]:
today = np.array([0, 1, 0])
today

array([0, 1, 0])

In [52]:
# @: matrix multiplication w/ numpy
today @ model # probability distribution of tomorrow

array([0.5, 0.3, 0.2])

In [55]:
# odds after 2 days
today @ np.linalg.matrix_power(model, 2)

array([0.56, 0.25, 0.19])

In [58]:
# ... after 10
today @ np.linalg.matrix_power(model, 10)

array([0.58064516, 0.24193548, 0.17741935])

In [61]:
# ... after 100
today @ np.linalg.matrix_power(model, 100)

array([0.58064516, 0.24193548, 0.17741935])

We can see after a time the model converges on stable probabilities.

Note: not all models do so, they can also become periodic

In [62]:
sunny = np.array([1, 0, 0])
rainy = np.array([0, 0, 1])

In [63]:
sunny @ np.linalg.matrix_power(model, 100)

array([0.58064516, 0.24193548, 0.17741935])

In [64]:
rainy @ np.linalg.matrix_power(model, 100)

array([0.58064516, 0.24193548, 0.17741935])